[build]
  command = "node build.js"
  publish = "."
  ignore = "git diff --quiet HEAD^ HEAD docs/ README.md"

[context.staging]
  command = "node build.js"
  publish = "."

[context.production]
  command = "node build.js"
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
